spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:debug}
  dir:
    ./logs